name: Main workflow
run-name: ${{ github.actor }} pushed new features
on: [push]
jobs:
    Code-Quality:
        runs-on: ubuntu-22.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@2.21.2
              with:
                php-version: '8.1'
                coverage: none
                tools: composer:v2
                extensions: mbstring, xml, json, pdo_mysql, pdo
            - name: Check PHP version
              run: php -v
            - name: Check Composer version
              run: composer -v
            - name: Validate composer files
              run: composer validate
            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir::$(composer config cache-files-dir) >> $GITHUB_OUTPUT"
            - name: Cache project dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install required dependencies
              run: composer install
            - name: Setup the local php security checker
              run: |
                curl -sSL https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_linux_amd64 -o /usr/local/bin/local-php-security-checker
                chmod +x /usr/local/bin/local-php-security-checker
            - name: GrumPHP analysis
              run: php ./vendor/bin/grumphp run
