name: Main workflow
run-name: ${{ github.actor }} pushed new features
on:
  push:
    branches:
      - main
      - develop
jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/composer@v6
        with:
          dev: no
          version: 2
      - name: Packages installation
        run: composer install
      - name: GrumPHP analysis
        run: php ./vendor/bin/grumphp run
