name: Main workflow
run-name: ${{ github.actor }} pushed new features
on:
    push:
        branches:
            - main
            - develop
jobs:
    Code-Quality:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Packages installation
              uses: php-actions/composer@v7
              with:
                  dev: no
                  version: 2
            - name: GrumPHP analysis
              run: php ./vendor/bin/grumphp run
