name: Unit tests workflow
run-name: ${{ github.actor }} tests code
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpunit
          extension: mbstring, xml, json, pdo_mysql, pdo
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache project dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install required dependencies
        run: composer install
      - name: Create database
        run: |
          composer require --dev symfony/orm-pack
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
        env:
            DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/mydb
      - name: Run unit tests
        uses: php-actions/phpunit@v3
        with:
          memory_limit: 2G
