name: Unit tests workflow
run-name: ${{ github.actor }} pushed
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpunit
      - name: Run unit tests
        uses: php-actions/phpunit@v3

