name: Unit tests workflow
run-name: ${{ github.actor }} pushed
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpunit
          extension: mbstring, xml, json, pdo_mysql, pdo
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache project dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install required dependencies
        run: composer install
      - name: Run unit tests
        uses: php-actions/phpunit@v3
        with:
          memory_limit: 2G
